# zmodload zsh/zprof # Uncomment for profiling

source "$HOME/.config/dotfiles-shell/main.sh"

# zprof # Uncomment for profiling

command -v atuin >/dev/null 2>&1 && eval "$(atuin init zsh --disable-up-arrow)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Wasmer
export WASMER_DIR="$HOME/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"

# >>> mamba initialize >>>
if command -v micromamba >/dev/null 2>&1; then
    export MAMBA_EXE="$(command -v micromamba)"
    export MAMBA_ROOT_PREFIX="$HOME/micromamba"
    __mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__mamba_setup"
    else
        alias micromamba="$MAMBA_EXE"  # Fallback on help from micromamba activate
    fi
    unset __mamba_setup
fi
# <<< mamba initialize <<<

export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"
