tools_dir: ~/.dotbins

platforms:
  linux:
    - amd64
    - arm64
  windows:
    - amd64

tools:
  delta: dandavison/delta
  duf: 
    repo: muesli/duf
    shell_code:
      powershell: |
        set-alias du duf.exe
  dust: bootandy/dust
  fd: sharkdp/fd
  git-lfs: git-lfs/git-lfs
  hyperfine: sharkdp/hyperfine
  rg: BurntSushi/ripgrep
  yazi: sxyazi/yazi

  bat:
    repo: sharkdp/bat
    shell_code:
      bash,zsh: |
        alias bat="bat --paging=never"
        alias cat="bat --plain --paging=never"
      powershell: |
        function cat { bat.exe --paging=never $args }
  direnv:
    repo: direnv/direnv
    shell_code:
      bash,zsh: |
        eval "$(direnv hook __DOTBINS_SHELL__)"
  eza:
    repo: eza-community/eza
    shell_code:
      bash,zsh: |
        alias l="eza --long --all --git --icons=auto"
        alias ll="eza --long --all --git --icons=auto"
        lt() { eza --long --all --git --icons=auto --sort modified --reverse --color=always $* | head -20; }
      powershell: |
        function l { eza.exe --long --all --git --icons=auto --color=always $args }
        function ll { eza.exe --long --all --git --icons=auto --color=always $args }
        function lt { eza --long --all --git --icons=auto --sort modified --reverse --color=always $args | head -20 }
  fzf:
    repo: junegunn/fzf
    shell_code:
      zsh: |
        source <(fzf --zsh)
      bash: |
        eval "$(fzf --bash)"
  lazygit:
    repo: jesseduffield/lazygit
    shell_code:
      bash,zsh: |
        alias lg="lazygit"
      powershell: |
        set-alias lg lazygit.exe
  micromamba:
    repo: mamba-org/micromamba-releases
    shell_code:
      bash,zsh: |
        alias mm="micromamba"
  starship:
    repo: starship/starship
    shell_code:
      bash,zsh: |
        eval "$(starship init __DOTBINS_SHELL__)"
      powershell: |
        Invoke-Expression (&starship init powershell)
  zoxide:
    repo: ajeetdsouza/zoxide
    shell_code:
      bash,zsh: |
        eval "$(zoxide init __DOTBINS_SHELL__)"
      powershell: |
        Invoke-Expression (& { (zoxide init powershell | Out-String) })
  atuin:
    repo: atuinsh/atuin
    shell_code:
      bash,zsh: |
        eval "$(atuin init __DOTBINS_SHELL__ --disable-up-arrow)"

  keychain:
    repo: funtoo/keychain
    asset_patterns: keychain

  uv:
    repo: astral-sh/uv
    binary_name: [uv, uvx]
    path_in_archive: [uv-*/uv, uv-*/uvx]
