source ~/git/dotfiles/configs/shell/main.sh

. "$HOME/.atuin/bin/env"
. "$HOME/.cargo/env"

if [ -e /home/wecker/.nix-profile/etc/profile.d/nix.sh ]; then . /home/wecker/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
