scan_timeout = 1

[time]
disabled = false

[gcloud]
disabled = true

[character]
success_symbol = '[|ψ❯](bold green) '
error_symbol = '[✗](bold red) '

[shell]
bash_indicator = "bash"
cmd_indicator = ""
fish_indicator = ""
powershell_indicator = ""
zsh_indicator = ""
unknown_indicator = ""
format = '[$indicator](cyan bold) '
disabled = false

