model: openai/qwen3-coder-next
openai-api-base: http://127.0.0.1:18023/v1
openai-api-key: local-vllm
verbose: false
show-diffs: false
pretty: true
stream: false
suggest-shell-commands: false
subtree-only: true
auto-commits: false
dirty-commits: false
# dark-mode: false
# edit-format: diff
# editor-edit-format: diff
read:
    - ~/.aider/CONVENTIONS.md
