personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approvals_reviewer = "user"

#[tui]
#vim_mode_default = true

[tui.keymap.editor]
insert_newline = "enter"

[tui.keymap.composer]
submit = ["ctrl-enter","ctrl-j"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/home/wecker/git/dotfiles"]
trust_level = "trusted"

[projects."/home/wecker/git/tinyAA"]
trust_level = "trusted"

[projects."/home/wecker/git/nanochat"]
trust_level = "trusted"

[projects."/home/wecker"]
trust_level = "trusted"

[projects."/home/wecker/git/ionics"]
trust_level = "trusted"

[projects."/home/wecker/git/sap/arch/third_party/cypress"]
trust_level = "trusted"

[projects."/home/wecker/git/qec_team"]
trust_level = "trusted"

[projects."/home/wecker/git/languages"]
trust_level = "trusted"

[projects."/mnt/d"]
trust_level = "trusted"

[projects."/home/wecker/git/Qwen3"]
trust_level = "trusted"

[projects."/home/wecker/.ssh"]
trust_level = "trusted"

[projects."/home/wecker/git/rustlab_llm"]
trust_level = "trusted"

[projects."/home/wecker/git/weckerAA"]
trust_level = "trusted"

[projects."/home/wecker/git"]
trust_level = "trusted"

[projects."/home/dbwz8/git/dotfiles"]
trust_level = "trusted"

[projects."/home/dbwz8/git/Qwen3"]
trust_level = "trusted"

[projects."/home/dbwz8/git/tinyAA"]
trust_level = "trusted"

[projects."/home/dbwz8/git/languages"]
trust_level = "trusted"

[projects."/home/dbwz8/git"]
trust_level = "trusted"

[projects."/mnt/d/data"]
trust_level = "trusted"

[notice]
hide_rate_limit_model_nudge = true
hide_full_access_warning = true

[plugins."github@openai-curated"]
enabled = true

[mcp_servers.ionq-mcp-gateway]
url = "https://prod-mcp-gateway.ionq.co/mcp"

[mcp_servers.ionq-mcp-gateway.tools.google-calendar_list_events]
approval_mode = "approve"

[mcp_servers.ionq-mcp-gateway.tools.slack-gateway-reader-mcp_list_conversations]
approval_mode = "approve"

[mcp_servers.ionq-mcp-gateway.tools.slack-backup_list_conversations]
approval_mode = "approve"

[mcp_servers.ionq-mcp-gateway.tools.google-drive_search_files]
approval_mode = "approve"

[mcp_servers.ionq-mcp-gateway.tools.google-drive_read_file_content]
approval_mode = "approve"
